### PR TITLE
palette terminal ease

### PR DESCRIPTION
**Pull request by alexpanter**
palette bash script to simplify the terminal usage for sorting student submissions.

### CODE REVIEW

**Comment by alexpanter** [comment]
I have tested this tool manually with 30-40 students (out of 158 on Software Development course). In roughly about 95% of the cases it works. Niklas suggested this might be an issue with Staffeli.

**Comment by oleks** [comment]
Instead of writing yet another wrapper, I think we should make this part of the staffeli CLI. See `staffeli/cli.py`.

**Comment by alexpanter** [comment]
yes I agree that would be a better idea. The bash syntax makes it difficult to maintain anyways. I might get to it, or someone else might do it first..

**Comment by oleks** [comment]
I will close this for now, but you are welcome to keep this around in a branch.

**Pull request closed without merging**
